version: '3.3'
  
services:

  park
    build:
      context: .
      dockerfile: ./park/Dockerfile
    image: pinecni/flume:v1
    hostname: park
    container_name: park
    environment:
      - AGENT_NAME=park
      - AGENT_FILE=/opt/flume/conf/park.conf
      - AGENT_CONF=/opt/flume/conf
    volumes:
      - ${CITYHUB}/flume/lib:/opt/flume/plugins.d/park/lib
      - ${CITYHUB}/flume/conf/park.conf:/opt/flume/conf/park.conf

